#!/usr/bin/env python3
"""
PyVault - Python source obfuscator/deobfuscator.

This tool obfuscates Python source files into a lambda-based loader with random-looking
byte strings, and can decrypt files generated by this tool back into the original source.

Author: https://github.com/davizofficial
"""

import os
import random
import re
import string
import zlib
from pathlib import Path

APP_NAME = "PyVault"
AUTHOR = "https://github.com/davizofficial"
HEADER_PREFIX = "# PyVault"
HEADER = f"{HEADER_PREFIX} - Coded by {AUTHOR}"
VERSION = "1.0.0"

# Lime green terminal color
LIME = "\033[38;2;50;255;50m"
DIM = "\033[2m"
RED = "\033[91m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
RESET = "\033[0m"


def clear_screen():
    os.system("cls" if os.name == "nt" else "clear")


def pause():
    input(f"\n{DIM}Press Enter to continue...{RESET}")


def color(text: str, code: str = LIME) -> str:
    return f"{code}{text}{RESET}"


def random_name(length=18):
    chars = string.ascii_letters + "_"
    return "_" + "".join(random.choice(chars) for _ in range(length))


def bytes_to_escape(data: bytes) -> str:
    return "".join("\\x%02x" % b for b in data)


def escape_to_bytes(text: str) -> bytes:
    return bytes(int(x, 16) for x in re.findall(r"\\x([0-9a-fA-F]{2})", text))


def xor_bytes(data: bytes, key: bytes) -> bytes:
    return bytes(data[i] ^ key[i % len(key)] for i in range(len(data)))


def rol8(value: int, shift: int) -> int:
    shift %= 8
    return ((value << shift) & 0xFF) | (value >> (8 - shift))


def ror8(value: int, shift: int) -> int:
    shift %= 8
    return (value >> shift) | ((value << (8 - shift)) & 0xFF)


def obfuscate_bytes(source: bytes):
    compressed = zlib.compress(source, level=9)

    key1 = os.urandom(random.randint(24, 64))
    key2 = os.urandom(random.randint(24, 64))
    shift = random.randint(1, 7)

    layer = xor_bytes(compressed, key1)
    layer = bytes(rol8(b, shift) for b in layer)
    layer = xor_bytes(layer, key2)

    return layer, key1, key2, shift


def deobfuscate_bytes(payload: bytes, key1: bytes, key2: bytes, shift: int):
    layer = xor_bytes(payload, key2)
    layer = bytes(ror8(b, shift) for b in layer)
    layer = xor_bytes(layer, key1)
    return zlib.decompress(layer)


def build_loader(payload: bytes, key1: bytes, key2: bytes, shift: int) -> str:
    n_payload = random_name()
    n_key1 = random_name()
    n_key2 = random_name()
    n_shift = random_name()
    n_zlib = random_name()
    n_i = random_name()

    payload_s = bytes_to_escape(payload)
    key1_s = bytes_to_escape(key1)
    key2_s = bytes_to_escape(key2)

    expr = (
        f"(((({n_payload}[{n_i}]^{n_key2}[{n_i}%len({n_key2})])>>{n_shift})|"
        f"((({n_payload}[{n_i}]^{n_key2}[{n_i}%len({n_key2})])<<(8-{n_shift}))&255))"
        f"^{n_key1}[{n_i}%len({n_key1})])"
    )

    return (
        f"{HEADER_PREFIX}:{shift} | {HEADER} | Version {VERSION}\n"
        f"(lambda {n_payload},{n_key1},{n_key2},{n_shift},{n_zlib}:"
        f"exec(compile("
        f"{n_zlib}.decompress(bytes([{expr} for {n_i} in range(len({n_payload}))])),"
        f"__file__,'exec')))"
        f'(b"{payload_s}",b"{key1_s}",b"{key2_s}",{shift},__import__(\'zlib\'))\n'
    )


def extract_parts(text: str):
    if HEADER_PREFIX not in text:
        raise ValueError("This file does not contain a valid PyVault header.")

    byte_strings = re.findall(r'b"((?:\\x[0-9a-fA-F]{2})+)"', text)
    if len(byte_strings) < 3:
        raise ValueError("Payload or keys were not found. Invalid PyVault file format.")

    payload = escape_to_bytes(byte_strings[0])
    key1 = escape_to_bytes(byte_strings[1])
    key2 = escape_to_bytes(byte_strings[2])

    match = re.search(r"# PyVault:(\d+)", text)
    if not match:
        raise ValueError("Shift value was not found in the PyVault header.")

    shift = int(match.group(1))
    if shift < 1 or shift > 7:
        raise ValueError("Invalid shift value.")

    return payload, key1, key2, shift


def show_banner():
    print(
        LIME
        + r"""
 /$$$$$$$            /$$    /$$                    /$$   /$$
| $$__  $$          | $$   | $$                   | $$  | $$
| $$  \ $$ /$$   /$$| $$   | $$ /$$$$$$  /$$   /$$| $$ /$$$$$$
| $$$$$$$/| $$  | $$|  $$ / $$/|____  $$| $$  | $$| $$|_  $$_/
| $$____/ | $$  | $$ \  $$ $$/  /$$$$$$$| $$  | $$| $$  | $$
| $$      | $$  | $$  \  $$$/  /$$__  $$| $$  | $$| $$  | $$ /$$
| $$      |  $$$$$$$   \  $/  |  $$$$$$$|  $$$$$$/| $$  |  $$$$/
|__/       \____  $$    \_/    \_______/ \______/ |__/   \___/
           /$$  | $$
          |  $$$$$$/
           \______/
"""
        + RESET
    )
    print(color("=" * 72))
    print(color(f"        {APP_NAME} v{VERSION} - Python Obfuscator"))
    print(color(f"        Coded by {AUTHOR}"))
    print(color("=" * 72))
    print(color("        1. Obfuscate Python (Encrypt)"))
    print(color("        2. Deobfuscate Python (Decrypt)"))
    print(color("=" * 72))


def ask_path(prompt: str) -> str:
    return input(color(prompt, CYAN)).strip().strip('"').strip("'")


def menu_obfuscate():
    clear_screen()
    show_banner()
    print(color("\n[ Obfuscate Python (Encrypt) ]\n", YELLOW))

    input_file = ask_path("Input Python file: ")
    if not input_file:
        print(color("Input cannot be empty.", RED))
        pause()
        return

    input_path = Path(input_file)
    if not input_path.exists():
        print(color(f"File not found: {input_path}", RED))
        pause()
        return

    if input_path.suffix.lower() != ".py":
        print(color("Warning: the input file does not use the .py extension.", YELLOW))

    default_output = input_path.with_name(input_path.stem + "_enc.py")
    output_file = ask_path(f"Output file [{default_output}]: ")
    output_path = Path(output_file) if output_file else default_output

    try:
        source = input_path.read_bytes()
        payload, key1, key2, shift = obfuscate_bytes(source)
        loader = build_loader(payload, key1, key2, shift)
        output_path.write_text(loader, encoding="utf-8")

        print(color("\n[OK] File successfully obfuscated.", LIME))
        print(color(f"Input : {input_path}", CYAN))
        print(color(f"Output: {output_path}", CYAN))
        print(color("\nRun the obfuscated file with:", YELLOW))
        print(color(f"python3 {output_path}", CYAN))
    except Exception as error:
        print(color(f"\n[ERROR] Obfuscation failed: {error}", RED))

    pause()


def menu_deobfuscate():
    clear_screen()
    show_banner()
    print(color("\n[ Deobfuscate Python (Decrypt) ]\n", YELLOW))

    input_file = ask_path("Input obfuscated file: ")
    if not input_file:
        print(color("Input cannot be empty.", RED))
        pause()
        return

    input_path = Path(input_file)
    if not input_path.exists():
        print(color(f"File not found: {input_path}", RED))
        pause()
        return

    stem = input_path.stem
    if stem.endswith("_enc"):
        stem = stem[:-4]
    default_output = input_path.with_name(stem + "_dec.py")

    output_file = ask_path(f"Output file [{default_output}]: ")
    output_path = Path(output_file) if output_file else default_output

    try:
        text = input_path.read_text(encoding="utf-8", errors="replace")
        payload, key1, key2, shift = extract_parts(text)
        source = deobfuscate_bytes(payload, key1, key2, shift)
        output_path.write_bytes(source)

        print(color("\n[OK] File successfully deobfuscated.", LIME))
        print(color(f"Input : {input_path}", CYAN))
        print(color(f"Output: {output_path}", CYAN))
    except Exception as error:
        print(color(f"\n[ERROR] Deobfuscation failed: {error}", RED))

    pause()


def main_menu():
    while True:
        clear_screen()
        show_banner()
        choice = (
            input(color("Choose an option [1/2] or q to quit: ", CYAN)).strip().lower()
        )

        if choice == "1":
            menu_obfuscate()
        elif choice == "2":
            menu_deobfuscate()
        elif choice in {"q", "quit", "exit"}:
            print(color("Goodbye.", LIME))
            break
        else:
            print(color("Invalid option.", RED))
            pause()


if __name__ == "__main__":
    main_menu()
